# Generated by Django 4.2.4 on 2023-08-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstatus',
            name='confirmedCases',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Confirmed Cases'),
        ),
        migrations.AlterField(
            model_name='covidstatus',
            name='death',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Deaths'),
        ),
        migrations.AlterField(
            model_name='covidstatus',
            name='recoveries',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Recoveries'),
        ),
    ]
